version: "3.8"
services:
    node01:
        image: limechain/as-substrate:stable
        ports:
            - target: 9933
              published: 9933
              mode: host
    node02:
        image: limechain/as-substrate:stable
        ports:
            - "0.0.0.0:9934:9933"
    
    node03:
        image: limechain/as-substrate:stable
        ports:
            - "0.0.0.0:9935:9933"
