version: "1.0.0"
services:
    node01:
        image: as-substrate:latest
        ports:
            - "9933"
            - "9944"
            - "30333"
        args:
            base-path: "tmp/node01"
            execution: "wasm"
            name: node01
            validator: ""
        