name: Integration Tests

on: [pull_request]
env:
  CARGO_TERM_COLOR: always

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install AssemblyScript Dependencies
      run: cd runtime && yarn install
    - name: Build AssemblyScript Runtime
      run: cd runtime && yarn run build
    - name: Build Rust Sandbox
      run: cd sandbox && cargo build --verbose
    - name: Run tests
      run: cd sandbox && cargo test --verbose
