name: Unit Tests

on: [push]
jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install AssemblyScript Dependencies
      run: cd runtime && yarn install
    - name: Run tests
      run: cd runtime && yarn run test:ci
  spec-builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Assemblyscript and other dependencies
      run: cd runtime/tools/spec-builder && yarn install
    - name: Build AssemblyScript module
      run: cd runtime/tools/spec-builder && yarn run asbuild
    - name: Run tests
      run: cd runtime/tools/spec-builder && yarn test
  e2e-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Run nodes
        run: docker-compose up -d
      - name: Install dependencies for testing
        run: cd e2e-tests && npm install
      - name: Run tests
        run: npm test