name: Unit Tests

on: [push]
jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install AssemblyScript Dependencies
      run: cd runtime && yarn install
    - name: Run tests
      run: cd runtime && yarn run test:ci
  spec-builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Assemblyscript and other dependencies
      run: cd runtime/tools/spec-builder && yarn install
    - name: Build AssemblyScript module
      run: cd runtime/tools/spec-builder && yarn run asbuild
    - name: Run tests
      run: cd runtime/tools/spec-builder && yarn test